### ISSUE TITLE
feat: MUSIC DASHBOARD 

### ISSUE THREAD

**Issue by astroicy** [blefnk/relivator-nextjs-template#43]
### Describe the feature you'd like to request

---
Could you develop a comprehensive music distribution dashboard using Next.js? This dashboard should have the following features:
---

### User Features:
1. **User Registration & Authentication:**
   - Users should be able to sign up, log in, and manage their accounts.
   - Implement authentication using JWT or OAuth to ensure security.

2. **Track Upload:**
   - Users should be able to upload their music tracks (in formats like MP3, WAV, etc.).
   - During the upload, users should be prompted to enter song metadata, including title, artist name, album, genre, release date, and cover art.

3. **Track Management:**
   - Users should have a dashboard to view, edit, or delete their uploaded tracks and metadata.
   - Option to categorize tracks by albums or playlists.

4. **Distribution Options:**
   - Users can select distribution platforms (e.g., Spotify, Apple Music, YouTube, etc.) where they want their tracks to be distributed.
   - Integrate options for scheduling releases and choosing territories for distribution.

5. **Analytics Dashboard:**
   - Users should have access to basic analytics showing the performance of their tracks, including streams, downloads, and revenue generated.
   - Charts and graphs to visualize this data.

6. **Payment Integration:**
   - Allow users to manage their revenue through the dashboard.
   - Integrate payment gateways like PayPal or Stripe for withdrawals and revenue distribution.

### Admin Features:
1. **Admin Panel:**
   - A secure admin panel where admins can log in and manage the entire platform.
   
2. **User Management:**
   - Admins should be able to view, modify, or delete any user's account or uploaded tracks.
   - Full access to edit metadata, reassign track ownership, or take down tracks if necessary.

3. **Track and Metadata Review:**
   - Admins should have the ability to review and approve/reject tracks before distribution if needed.
   - Option to flag or highlight tracks for potential copyright issues.

4. **Analytics Overview:**
   - Admins should have access to a global analytics dashboard showing platform-wide statistics like total uploads, active users, and revenue generated.
   - Ability to view detailed analytics for individual users and tracks.

5. **Distribution Management:**
   - Admins should have the ability to manually trigger distribution to different platforms or rollback distributions if there are issues.
   - Integration with various distribution services and the ability to monitor their statuses.

6. **Customizable Settings:**
   - Admins should be able to set platform-wide settings, such as accepted file formats, maximum upload size, and other upload restrictions.

7. **Support and Communication:**
   - Implement a system where admins can communicate directly with users, such as through a messaging system or support tickets.
   - Admins should have the ability to send platform-wide announcements.

### Design & UI:
- The UI should be modern, responsive, and intuitive, ensuring a seamless user experience across devices.
- Use a clean and minimalistic design with attention to usability, ensuring users can easily navigate the dashboard.
- Include dark and light mode options for user preference.

### Describe the solution you'd like to see

Please

### Additional information

✨

**Comment by blefnk** [comment]
Hi! Please reach out to me on the following platform: [https://fiverr.com/blefnk](https://fiverr.com/blefnk)
